# Generated by Django 6.0.3 on 2026-04-08 05:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('club', models.CharField(db_index=True, max_length=100)),
                ('source', models.CharField(choices=[('WEEKUK', '위꾹'), ('SPONET', '스포넷'), ('NEARMINTON', '우동배'), ('FACECOK', '페이스콕'), ('BAEF', '배프')], max_length=20)),
                ('external_uid', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('region_raw', models.CharField(blank=True, help_text='수집된 원본 장소 텍스트', max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', '검수중'), ('ongoing', '접수/진행중'), ('finished', '종료')], default='draft', max_length=10)),
                ('source', models.CharField(choices=[('WEEKUK', '위꾹'), ('SPONET', '스포넷'), ('NEARMINTON', '우동배'), ('FACECOK', '페이스콕'), ('BAEF', '배프')], max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(max_length=15, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('following_players', models.ManyToManyField(blank=True, related_name='followers', to='core.player')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('NOTICE', '공지'), ('UPDATE', '업데이트'), ('EVENT', '이벤트')], default='NOTICE', max_length=10)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('show_as_page', models.BooleanField(default=False)),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='낮은 숫자가 먼저 노출됩니다.')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament')),
            ],
            options={
                'verbose_name': '금주의 대회',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlayerDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('category_age_band', models.CharField(blank=True, max_length=50, null=True)),
                ('category_level', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.IntegerField(blank=True, help_text='대회 순위 (예: 1, 2, 3)', null=True)),
                ('win_count', models.IntegerField(default=0)),
                ('loss_count', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('ranking_point', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='core.player')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tournament')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('player', 'date')},
            },
        ),
    ]
