# Generated by Django 6.0.3 on 2026-04-02 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tournament_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='created_at',
            new_name='publish_at',
        ),
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('NOTICE', '공지'), ('UPDATE', '업데이트'), ('EVENT', '이벤트')], default='NOTICE', max_length=10),
        ),
        migrations.AlterField(
            model_name='notice',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FeaturedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='낮은 숫자가 먼저 노출됩니다.')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament')),
            ],
            options={
                'verbose_name': '금주의 대회',
                'ordering': ['order'],
            },
        ),
    ]
