# Generated by Django 6.0.3 on 2026-04-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_playerdailystats_end_date_playerdailystats_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerdailystats',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='playerdailystats',
            name='venue',
        ),
        migrations.AddField(
            model_name='tournament',
            name='venue',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
