# Generated by Django 6.0.3 on 2026-04-02 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_news_rename_created_at_notice_publish_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdailystats',
            name='category_age_band',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='playerdailystats',
            name='category_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='playerdailystats',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='playerdailystats',
            name='rank',
            field=models.IntegerField(blank=True, help_text='대회 순위 (예: 1, 2, 3)', null=True),
        ),
        migrations.AddField(
            model_name='playerdailystats',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tournament'),
        ),
    ]
