# Generated by Django 6.0.3 on 2026-04-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_playerdailystats_end_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerdailystats',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='playerdailystats',
            name='is_heuristic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerdailystats',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='external_uid',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='playerdailystats',
            name='rank',
            field=models.CharField(blank=True, help_text='대회 순위 (예: 1, 우승, 3위 등 문자가 들어올 수 있음)', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='playerdailystats',
            index=models.Index(fields=['-date', 'is_verified'], name='core_player_date_974093_idx'),
        ),
    ]
