# Generated by Django 6.0.3 on 2026-04-03 07:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_playerdailystats_category_age_band_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='show_as_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notice',
            name='publish_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
