# Generated by Django 5.1.7 on 2026-04-16 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_playerdailystats_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_win', models.BooleanField(default=False)),
                ('my_score', models.IntegerField(default=0)),
                ('op_score', models.IntegerField(default=0)),
                ('opponent_names', models.CharField(blank=True, max_length=255, null=True)),
                ('opponent_club', models.CharField(blank=True, max_length=255, null=True)),
                ('daily_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.playerdailystats')),
            ],
            options={
                'db_table': 'match_record',
                'ordering': ['id'],
            },
        ),
    ]
