# Generated by Django 5.1.7 on 2026-04-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_matchrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrecord',
            name='final_status',
            field=models.CharField(blank=True, help_text='최종 상태 (우승, 본선 진출, 예선 탈락 등)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='matchrecord',
            name='gain_point',
            field=models.IntegerField(default=0, help_text='득실차'),
        ),
    ]
