# Generated by Django 6.0.3 on 2026-04-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notice_expire_at_notice_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='region_raw',
            field=models.CharField(blank=True, help_text='수집된 원본 장소 텍스트', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='source',
            field=models.CharField(choices=[('WEEKUK', '위꾹'), ('SPONET', '스포넷'), ('NEARMINTON', '우동배'), ('FACECOK', '페이스콕'), ('BAEF', '배프')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='external_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='source',
            field=models.CharField(choices=[('WEEKUK', '위꾹'), ('SPONET', '스포넷'), ('NEARMINTON', '우동배'), ('FACECOK', '페이스콕'), ('BAEF', '배프')], max_length=20),
        ),
    ]
