# Generated by Django 6.0.3 on 2026-04-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_matchrecord_final_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_stats_fetched',
            field=models.BooleanField(db_index=True, default=False, help_text='전적 수집 완료 여부. True이면 collect_stats가 스킵함.'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='stats_fetched_at',
            field=models.DateTimeField(blank=True, help_text='전적 수집이 완료된 시각 (디버깅 및 감사 로그용)', null=True),
        ),
        migrations.AlterField(
            model_name='playerdailystats',
            name='is_heuristic',
            field=models.BooleanField(default=False, help_text='추측성 수집 데이터 여부 (프론트 경고 문구 출력)'),
        ),
        migrations.AlterField(
            model_name='playerdailystats',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='관리자 승인 후 True → 프론트 노출'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='region_raw',
            field=models.CharField(blank=True, help_text='수집된 원본 장소 텍스트 (정규화 전)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='source',
            field=models.CharField(choices=[('WEEKUK', '위꾹'), ('SPONET', '스포넷'), ('NEARMINTON', '우동배'), ('FACECOK', '페이스콕'), ('BAEF', '배프')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('draft', '검수중'), ('ongoing', '접수/진행중'), ('finished', '종료')], db_index=True, default='draft', help_text="collect_stats 커맨드가 'finished'인 것만 전적 수집 대상으로 삼음", max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='tournament',
            unique_together={('source', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['status', 'is_stats_fetched'], name='core_tourna_status_5f7635_idx'),
        ),
    ]
