# Generated by Django 6.0.3 on 2026-04-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tournament_is_stats_fetched_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tournament',
            name='core_tourna_status_5f7635_idx',
        ),
        migrations.AlterUniqueTogether(
            name='tournament',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.CharField(blank=True, db_index=True, default='', help_text='선수 급수 (최근 대회 기준, 예: 자강/A조/B조/C조/D조)', max_length=20),
        ),
        migrations.AlterField(
            model_name='playerdailystats',
            name='is_heuristic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playerdailystats',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_stats_fetched',
            field=models.BooleanField(db_index=True, default=False, help_text='전적 수집 완료 여부'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='region_raw',
            field=models.CharField(blank=True, help_text='수집된 원본 장소 텍스트', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='source',
            field=models.CharField(choices=[('WEEKUK', '위꾹'), ('SPONET', '스포넷'), ('NEARMINTON', '우동배'), ('FACECOK', '페이스콕'), ('BAEF', '배프')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='stats_fetched_at',
            field=models.DateTimeField(blank=True, help_text='전적 수집 완료 시각', null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('draft', '검수중'), ('ongoing', '접수/진행중'), ('finished', '종료')], default='draft', max_length=10),
        ),
    ]
