# Generated by Django 6.0.3 on 2026-04-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_player_level_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdailystats',
            name='partner_level',
            field=models.CharField(blank=True, default='', help_text='복식 파트너 급수', max_length=20),
        ),
        migrations.AddField(
            model_name='playerdailystats',
            name='partner_name',
            field=models.CharField(blank=True, default='', help_text='복식 파트너 이름', max_length=100),
        ),
        migrations.AddField(
            model_name='playerdailystats',
            name='team_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='playerdailystats',
            name='team_type_flag',
            field=models.CharField(blank=True, default='', help_text='S=단식 D=복식 M=혼합복식', max_length=10),
        ),
    ]
