# Generated by Django 6.0.3 on 2026-04-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_player_level_partner_team_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdailystats',
            name='partner_club',
            field=models.CharField(blank=True, default='', help_text='복식 파트너 동호회', max_length=100),
        ),
    ]
