# Generated by Django 6.0.3 on 2026-04-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tournament_stats_collected'),
        ('core', '0011_add_partner_club'),
    ]

    operations = [
    ]
